version: '3.7'

volumes:
  postgres:
  logs:

services:
  ts-node-docker:
    build: .
    volumes:
      - logs:/app/log.txt
      - ./src:/app/src
    container_name: node
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    networks:
      - my_network
  postgres:
    build: ./db/
    networks:
      - my_network
    image: postgres:9.5.13-alpine
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - ${ORM_PORT}:${ORM_PORT}
    environment:
      POSTGRES_USER: ${ORM_USERNAME}
      POSTGRES_PASSWORD: ${ORM_PASSWORD}
      POSTGRES_DB: ${ORM_DATABASE}
    restart: always

networks:
  my_network:
    driver: bridge
